### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JamesDAdams** [adyanth/traefik-container-manager#9]
Hi, i try to use the Traefik plugin but i have this error if i consult the webpage :

`Unexpected status answer from Manager service`

**Comment by JamesDAdams** [comment]
In Container Manager : 

```
Service: &{name:whoami timeout:5 host: path: time:0xc0001a4230 isHandled:false}
Containers []
Error: no containers found
```

**Comment by adyanth** [comment]
Can you tell me if you have the whoami container running with all the needed labels?

**Comment by adyanth** [comment]
Looks like the readme example is not using the right ones :) It should be `traefik-container-manager.name`. 

Edit: I have updated the readme now. Let me know if that fixes the issue.

**Comment by JamesDAdams** [comment]
Yes it works after 5s the whoami container is stopped by cons once the container is off when I come back to the whoami url it does not turn on again :(

**Comment by adyanth** [comment]
It should. The 1st request may fail with a 404/503, but the 2nd one should succeed. At least that is what I remember the behaviour was.

**Comment by JamesDAdams** [comment]
Not for me 
![Sans titre](https://user-images.githubusercontent.com/20860324/130323142-5c980a9d-358b-4992-abf5-b53275ab3373.png)

**Comment by JamesDAdams** [comment]
**Manager :** 

```
- traefik.enable=true
- traefik.http.routers.manager.entrypoints=websecure
- traefik.http.routers.manager.rule=Host(`manager.domainename.com`)
- traefik.http.routers.manager.priority=1
- traefik.http.middlewares.manager.errors.status=404
- traefik.http.middlewares.manager.errors.service=manager
- traefik.http.middlewares.manager.errors.query=/
- traefik.http.routers.manager.middlewares=manager-timeout
- traefik.http.services.manager.loadbalancer.server.port=80
- traefik.http.middlewares.manager-timeout.plugin.traefik-container-manager.name=generic-container-manager
```

**Whoami**

```
- traefik.enable=true
- traefik.http.routers.whoami.entrypoints=websecure
- traefik.http.routers.whoami.rule=Host(`whoami.domainename.com`)
- traefik.http.routers.whoami.middlewares=whoami-timeout
- traefik.http.services.whoami.loadbalancer.server.port=80
- traefik.http.middlewares.whoami-timeout.plugin.traefik-container-manager.timeout=30
- traefik.http.middlewares.whoami-timeout.plugin.traefik-container-manager.name=whoami
- traefik.http.middlewares.whoami-timeout.plugin.traefik-container-manager.serviceUrl=http://192.168.1.100:10000/api #Local url from Manager
- traefik-container-manager.name=whoami
```

**Comment by adyanth** [comment]
Config looks right. The below ones should redirect you to the manager service as per config [here](https://doc.traefik.io/traefik/v2.3/middlewares/errorpages/). But you are still getting the 404 by traefik. Can you check the logs from the manager and traefik itself, to see if they report anything?
```yaml
- traefik.http.middlewares.manager.errors.status=404
- traefik.http.middlewares.manager.errors.service=manager
- traefik.http.middlewares.manager.errors.query=/
```

**Comment by JamesDAdams** [comment]
In the traefik.log i have this : 

`time="2021-08-21T17:09:36+02:00" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: write udp 127.0.0.1:35066->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger`

**Comment by adyanth** [comment]
No, that seems to be unrelated to the issue ([Info on Jaegar](https://doc.traefik.io/traefik/observability/tracing/jaeger/))

When a 404 happens, the request is sent to the manager container, which is intercepted by the middleware, which talks to the manager container out of band.

You seem to have set a custom serviceUrl with an IP address. May I ask why that is? Where is the manager container, and why were you not able to just reference it by name? Seems like it might be working fine though, since the container was stopped properly. 

If you could share the traefik and the manager logs, I might be able to help you. The traefik logs would contain the middleware logs too, and the manager would log what it received.

**Comment by JamesDAdams** [comment]
**You seem to have set a custom serviceUrl with an IP address.** : 
it is the ip of the container manager to not go through a domain name

**If you could share the traefik and the manager logs** : 
I reset the log file then I made a request to whoami and there was nothing in the logs

**Comment by JamesDAdams** [comment]
and yes the problem must come from the interception
of the request by manager because when I refresh the page and I have the 404 error in manager log I have nothing

**Comment by JamesDAdams** [comment]
**You seem to have set a custom serviceUrl with an IP address. :**
i edit serviceURL for http://manager:10000 same problem

**Comment by adyanth** [comment]
Yeah, that should be okay, since the container was indeed stopped. I'm not sure here why the request is not sent to the middleware or the manager when a 404 was hit. I will try to set this up myself tomorrow and see if something has changed with traefik itself which might be causing this.

**Comment by JamesDAdams** [comment]
> Yeah, that should be okay, since the container was indeed stopped. I'm not sure here why the request is not sent to the middleware or the manager when a 404 was hit. I will try to set this up myself tomorrow and see if something has changed with traefik itself which might be causing this.

Ok Thanks :)

**Comment by JamesDAdams** [comment]
if it can help, my traefik.toml : 

```
# /apps/traefik/traefik.toml
[api]
  dashboard = true
  insecure = true
  
[tracing]

[log]
  filePath = "/etc/traefik/acme/traefik.log"
  
[pilot]
    token = "XXXX"
[experimental.plugins.traefik-container-manager]
  moduleName = "github.com/adyanth/traefik-container-manager"
  version = "v0.1.2"
  
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"
          permanent = true

  [entryPoints.pterodactyl]
    address = ":8443"
      [entryPoints.pterodactyl.http.tls]
        certResolver = "default"
	
  [entryPoints.peertube]
    address = ":1935"

  [entryPoints.websecure]
    address = ":443"
      [entryPoints.websecure.http.tls]
        certResolver = "default"
		

[providers]
  [providers.docker]
    watch = true
    exposedByDefault = false
    network = "web"

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "mail@domainename.com"
      storage = "/etc/traefik/acme/acme.json"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
    [certificatesResolvers.default.acme.tlsChallenge]
[serversTransport]
  insecureSkipVerify = true
```

**Comment by JamesDAdams** [comment]
I think I found the problem

I think you have planned this plugin so that for example the manager's address is https://manager.domainename.com and whoami is on the url https://manager.domainename.com/whoami the concern is that me the 2 services are on 2 sub domain

**Manager :** https://manager.myDomaineName.com
**Whoami  :** https://Whoami.myDomaineName.com

**Comment by adyanth** [comment]
Ahh yes. That support was added later on to the manager container, but I guess I forgot to document the changes. I was able to use it just fine with subdomains too. Please add this label to your whoami container and let me know if it works.

I would also recommend you to re pull the manager image to make sure it uses the latest image.
```
labels:
  - ...
  - traefik-container-manager.host=whoami # subdomain or the complete domain name. code checks for prefix match.
```

**Comment by JamesDAdams** [comment]
> Ahh yes. That support was added later on to the manager container, but I guess I forgot to document the changes. I was able to use it just fine with subdomains too. Please add this label to your whoami container and let me know if it works.
> 
> I would also recommend you to re pull the manager image to make sure it uses the latest image.
> 
> ```
> labels:
>   - ...
>   - traefik-container-manager.host=whoami # subdomain or the complete domain name. code checks for prefix match.
> ```

ok thanks, i download the new image and i have rebuild and i add the new labels in the whoami container like this : 

`- traefik-container-manager.host=whoami.domaineName.com`

but it's doesn't work :(

**Comment by adyanth** [comment]
Could you try with the `docker-compose.yml` and the `traefik.yml` provided in the repo and see if that works? Because that works for me. If that works for you too, then we need to look at your configuration specifically.

**Comment by JamesDAdams** [comment]
> Could you try with the `docker-compose.yml` and the `traefik.yml` provided in the repo and see if that works? Because that works for me. If that works for you too, then we need to look at your configuration specifically.

ok i will test in the week, because your docker compose will not work directly i have to config it with my domain name

**Comment by JamesDAdams** [comment]
ok it's work :D 

I was just wrong in the `traefik.http.routers.manager.rule`, i add HostRegexp(`{host:.+}`) and it's work thanks :)

**Comment by adyanth** [comment]
Aha! Nice catch! Thanks for letting me know that here. Will proceed to close this issue.
